apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api.fullname" .}}-api
  labels:
    app: {{ include "python-api.fullname" .}}-api
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.api.type }} 
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }} 
      protocol: TCP
    - name: metrics
      port: 9100

  selector:
    app: {{ include "python-api.fullname" .}}-api
    