apiVersion: monitoring.coreos.com/v1
kind: serviceMonitor
metadata:
  name: {{ include "python-api.fullname" . }}-monitor
  namespace: observability
spec:
  selector:
    matchLabels:
      app: {{ include "python-api.fullname" . }}-api
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
